import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@/app/globals.css'
import { ThemeRegistry } from "./ThemeProvider";
import { Box, Stack } from "@mui/material";
import NextAuthWrapper from "@/library/next.auth.wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeRegistry>
          <Stack minHeight={"100vh"}>
              <Box component={"main"} flexGrow={1}>
                <NextAuthWrapper>
                  {children} 
                </NextAuthWrapper> 
              </Box>
          </Stack>
        </ThemeRegistry>
      </body>
    </html>
  );
}
